let carrinho = {
  itens: [],
  preco: 0,
};

const vinhos = [
  { id: 1, nome: "Chardonnay", tipo: "Branco", preco: 50 },
  { id: 2, nome: "Cabernet Sauvignon", tipo: "Tinto", preco: 60 },
  { id: 3, nome: "Merlot", tipo: "Tinto", preco: 45 },
  { id: 4, nome: "Pinot Noir", tipo: "Tinto", preco: 55 },
  { id: 5, nome: "Riesling", tipo: "Branco", preco: 40 },
  { id: 6, nome: "Sauvignon Blanc", tipo: "Branco", preco: 35 },
  { id: 7, nome: "Malbec", tipo: "Tinto", preco: 65 },
  { id: 8, nome: "Syrah", tipo: "Tinto", preco: 50 },
  { id: 9, nome: "Zinfandel", tipo: "Tinto", preco: 45 },
  { id: 10, nome: "Gewürztraminer", tipo: "Branco", preco: 55 },
  { id: 11, nome: "Sangiovese", tipo: "Tinto", preco: 60 },
  { id: 12, nome: "Tempranillo", tipo: "Tinto", preco: 40 },
  { id: 13, nome: "Grenache", tipo: "Tinto", preco: 50 },
  { id: 14, nome: "Viognier", tipo: "Branco", preco: 45 },
  { id: 15, nome: "Moscato", tipo: "Branco", preco: 35 },
  { id: 16, nome: "Carmenere", tipo: "Tinto", preco: 55 },
  { id: 17, nome: "Petit Verdot", tipo: "Tinto", preco: 60 },
  { id: 18, nome: "Chenin Blanc", tipo: "Branco", preco: 40 },
  { id: 19, nome: "Gruner Veltliner", tipo: "Branco", preco: 50 },
  { id: 20, nome: "Nebbiolo", tipo: "Tinto", preco: 65 },
  { id: 21, nome: "Mourvedre", tipo: "Tinto", preco: 45 },
  { id: 22, nome: "Albarino", tipo: "Branco", preco: 55 },
  { id: 23, nome: "Cinsault", tipo: "Tinto", preco: 40 },
  { id: 24, nome: "Verdejo", tipo: "Branco", preco: 50 },
  { id: 25, nome: "Gamay", tipo: "Tinto", preco: 45 },
  { id: 26, nome: "Sangiovese Grosso", tipo: "Tinto", preco: 60 },
  { id: 27, nome: "Garganega", tipo: "Branco", preco: 35 },
  { id: 28, nome: "Montepulciano", tipo: "Tinto", preco: 55 },
  { id: 29, nome: "Vermentino", tipo: "Branco", preco: 40 },
  { id: 30, nome: "Barbera", tipo: "Tinto", preco: 50 },
  { id: 31, nome: "Cortese", tipo: "Branco", preco: 45 },
  { id: 32, nome: "Negroamaro", tipo: "Tinto", preco: 60 },
  { id: 33, nome: "Falanghina", tipo: "Branco", preco: 35 },
  { id: 34, nome: "Bonarda", tipo: "Tinto", preco: 55 },
  { id: 35, nome: "Trebbiano", tipo: "Branco", preco: 40 },
];

let listaDeDesejos = [];